// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wgcppyixzftmifzliyuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnY3BweWl4emZ0bWlmemxpeXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjE2NjksImV4cCI6MjA3MDMzNzY2OX0.pXgwofNmY7HyeYi-JZYxWcQYKCME2mjFcTclpPRuOuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);